
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "transport-cba"
version = "0.1"
description = "Cost-benefit analysis of infrastructure projects"
readme = "README.md"
authors = [{ name = "Peter Vanya", email = "peter.vanya@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["cost", "benefit", "analysis", "roi", "transport"]
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.16, <2",
    "pandas>=0.24, <1.3",
    "numpy-financial>=1.0.0",
    "xlrd>=1.2.0",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["transport_cba"]

[project.urls]
Homepage = "https://github.com/transport-cba/transport-cba"
